### PR TITLE
Additional deb control fields

### PR DESCRIPTION
**Pull request by bmoyles**
New pull (was https://github.com/nebula-plugins/gradle-ospackage-plugin/pull/86 ) against gradle-2.2 branch (cc @bmuschko @coryb @rspieldenner @quidryan @jkschneider @DanielThomas )

### CODE REVIEW

**Comment by bmuschko** [comment]
Done! Thanks for reopening it against `gradle-2.2`.

**Comment by bmuschko** [comment]
@bmoyles Would you mind updating the changelog file as well so we don't forget what has changed?

**Comment by bmoyles** [comment]
Will do!

**Comment by bmuschko** [comment]
Thanks!

**Pull request merged**
