### PR TITLE
Make SystemPackagingTask archive file config gradle 7 compatible

### PR DESCRIPTION
**Pull request by breskeby**
Using convention mapping has been deprecated in Gradle 7.1. This PR makes the task specific archive file configuration Gradle 7.1 compliant.

### CODE REVIEW

**Comment by breskeby** [comment]
Anyone looking into this and has feedback? Would love to see that merged and published

**Comment by DanielThomas** [comment]
Thanks for this @breskeby. Looks fine to me. @chali has been handling our Gradle 7 compatibility work, I'll leave it for him to merge so I don't step on his toes.

**Comment by rpalcolea** [comment]
Hi @breskeby , thanks again for this change

8.6.1 is out and should contain both of your contributions

**Comment by breskeby** [comment]
Awesome thanks!

**Pull request merged**
