### PR TITLE
Additional deb control fields

### PR DESCRIPTION
**Pull request by bmoyles**
This adds support for the Conflicts, Recommends, Suggests, Enhances, Pre-Depends, Breaks, and Replaces control fields in deb packages. (cc @coryb @quidryan @rspieldenner )

### CODE REVIEW

**Comment by bmoyles** [comment]
More info here
https://www.debian.org/doc/debian-policy/ch-relationships.html

**Comment by quidryan** [comment]
LGTM

**Comment by bmuschko** [comment]
@bmoyles Is this change needed for Gradle 1.12? I also upgraded the JDeb library. Would you mind rebasing your pull request and check if the tests still pass?

**Comment by bmoyles** [comment]
@bmuschko We can make it 2.x only. Should I rebase against the gradle-2.2 branch then?

**Comment by bmuschko** [comment]
@bmoyles That would be great. Thanks!

**Pull request closed without merging**
