### PR TITLE
Added preTrans and postTrans for RPM packages

### PR DESCRIPTION
**Pull request by dwendelen**
Closes issue #145 
Replaces PR #163 which failed because of error 137 on travis

### CODE REVIEW

**Comment by dwendelen** [comment]
Also failed because travis closed with error 137, like it did in PR #170 and PR #163

**Comment by dwendelen** [comment]
@nadavc I saw in PR #170 that you fixed a travis problem (error 137). I have the same issue here, can you fix it as well for this PR?

Thanks in advance

**Comment by nadavc** [comment]
It looks like I was able to get the build working again. Please rebase from master to re-run the build.

**Comment by dwendelen** [comment]
Ok, it works now. Thanks for the effort.

**Comment by nadavc** [comment]
LGTM. Merging!

**Pull request merged**
