### PR TITLE
Avoid "Cannot invoke method toLowerCase() on null object" if arch is set...

### PR DESCRIPTION
**Pull request by aadamovich**
... to null on buildRpm task

### CODE REVIEW

**Comment by quidryan** [comment]
Thanks. Can you add a test that shows what happens if arch is empty/null? We might need more protections here.

**Comment by bmuschko** [comment]
@aadamovich Would love to merge it. Would you mind adding a test for this?

**Comment by bmuschko** [comment]
@quidryan Instead of checking for `null`, I think I'd rather make the [arch field in SystemPackagingExtension](https://github.com/nebula-plugins/gradle-ospackage-plugin/blob/gradle-1.12/src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingExtension.groovy#L91) mandatory by removing `@Optional` and assign `Architecure.NO_ARCH` as default value. Sounds good? BTW: `org.redline_rpm.header.Architecture` should not be used in `SystemPackagingExtension` as it should be library-agnostic.

**Comment by aadamovich** [comment]
I think it should be possible to allow both ".noarch." in the name of the package and an empty string that will just not add an architecture component to the package name.

I will try to add the test next week.

**Comment by quidryan** [comment]
Some relevant changes just went in via #95 . We can now use Strings for arch. And I believe it can be null now. Though that would be a good test.

**Comment by quidryan** [comment]
But as it is, this won't merge anymore.

**Pull request closed without merging**
