### PR TITLE
Added support for signing packages

### PR DESCRIPTION
**Pull request by dmnjohns**
Enables signing of DEB/RPM package files themselves, rather than, say, providing a signature file alongside a package.

### CODE REVIEW

**Comment by rspieldenner** [comment]
looks good, I'll need to check if the createDeb(Compression.GZIP) vs makeDeb make a difference for us. If no problem will probably merge and release Monday.

**Comment by dmnjohns** [comment]
Sounds great.

makeDeb by default will use GZIP compression, but thinking about it now, I could explicitly call setCompression(Compression.GZIP) before calling makeDeb.

I'll make that change if it is preferred, just let me know.

**Comment by dmnjohns** [comment]
I went ahead and added that call for the sake of clarity.

**Comment by farrukhnajmi** [comment]
I am in need of this feature and wondering when we may have a release that includes it? I would be glad to help with anything I can do to help facilitate the release of the feature. TIA and thanks for a great plugin.

**Comment by sghill** [comment]
@farrukhnajmi This feature has already been released and was first available in v3.4.0.

The pull request was merged almost a year ago. We use the [nebula-plugins/nebula-release-plugin](https://github.com/nebula-plugins/nebula-release-plugin) for releases, which always creates a git tag. By viewing the commit https://github.com/nebula-plugins/gradle-ospackage-plugin/commit/e5ee61891655f20273e1ff2ff5aa19ea2402a080, you can see which tags it appears in. 

A [walkthrough](https://github.com/nebula-plugins/gradle-ospackage-plugin/issues/179#issuecomment-269423747) for RPMs and Debs was provided on #179 that may be of interest.

**Pull request merged**
