### PR TITLE
Initial draft of using a OS-package spec for create a Dockerfile.

### PR DESCRIPTION
**Pull request by bmuschko**
Some comments to this approach:

* I think we are encountering an impedance mismatch by trying to integration the creation of a Docker image.
   * We are not actually creating an archive, we are only using the copy spec.
   * Most of the methods in the CopyAction do not apply.
   * When creating a Dockerfile, ordering matters. That's not the case for creating an archive. This might become a problem for users.
* I didn't create a dependency on my Docker plugin for various reasons.
    * I don't want to drag in the whole dependency tree.
    * Creating the Dockerfile doesn't require the Docker remote API. If the user decides to use the Docker remote API (e.g. for building the image), then they can add the plugin on top.
    * Reusing the existing `Dockerfile` custom task from my plugin doesn't work well with the model we have for the OS package plugin (e.g. some methods like `from` would conflict with the CopySpec method; we need to extends `SystemPackagingTask`).

Let me know what you think.

### CODE REVIEW

**Comment by quidryan** [comment]
I would have expected buildDocker to build a docker image, not just a Docker file. We build control files on the file for the deb support, but the actual file is in implementation detail, the end goal is a binary. I think you need to bring this support further, to actually run a docker build.

**Comment by bmuschko** [comment]
That's easy to achieve but it creates the automatic dependency on another plugin which I tried to avoid. 

_Examples:_

* You will need to make sure that the Docker plugin is compatible with the Gradle version used for this plugin. This will result in additional maintenance work.
* Changes in the API of the Docker plugin will propagate down to this plugin.
* If users (for whatever reason) do not want to use then Docker's remote API and instead want to use system Docker commands, then they can't because that not how my plugin works.
* Users of this plugin will need to know about the configuration of the Docker plugin in detail.

Let me update the pull request with your requested change and then we go from there.

One more side note: In the long run you might want to fully decouple the Deb, RPM and Docker OSpackage plugin from the system package plugin.

**Comment by bmuschko** [comment]
@quidryan Would you mind reviewing this pull request?

**Comment by bmuschko** [comment]
@rspieldenner Can you please merge it up into the other branches as well?

**Pull request merged**
